NomeDoCliente = input('Digite o nome do cliente: ')
DiaDeVencimento = input('Digite o dia do vencimento: ')
MesDoVencimento = input('Digite o mes do vencimento: ')
ValorDaFatura = input('Digite o valor da fatura: ')
print("Olá", NomeDoCliente)
print("A sua fatura com vencimento em", DiaDeVencimento, "de", MesDoVencimento, "no valor de", ValorDaFatura, "está fechada.")
